FROM registry.gitlab.com/deliverycom/dapi-docker:frontend-base

# Frontend should currently be only a data container/volume unless they decide to serve their own data
ADD src.tgz /var/www/deliveryApi/new-admin
